{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "How_to_download_in_COLAB.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "mount_file_id": "1CD5KAgQzEa4j3XO2ezYK8lrR7VEnuyAp",
      "authorship_tag": "ABX9TyPVDO2vt8m3+S+PIOOmZ3Dl",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/BragatteMAS/Python/blob/master/How_to/How_to_download_in_COLAB.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "WXye7tHnHdDG"
      },
      "source": [
        "Create file from COLAB"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7hcCxUbXG0Lu"
      },
      "source": [
        "!mkdir -p \"/content/drive/MyDrive/9.Colab Notebooks/RedeAnaliseCOVID-19/Codes/vacinas\""
      ],
      "execution_count": 1,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "-ty1BvuWHfX1"
      },
      "source": [
        "Save download from URL direct in googledrive | COLAB\n",
        "\n",
        "Put the url right after de path - if the path are not inform will be a temp file"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Ey0ks8MFG0TX"
      },
      "source": [
        "# !wget -P \"/content/drive/MyDrive/9.Colab Notebooks/RedeAnaliseCOVID-19/Codes/vacinas\" https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-04-28/uf%3DRS/part-00000-7ab10ee1-6a0f-4ed9-b84c-9afb98b4efc2.c000.csv"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6kmOoG7cG0az"
      },
      "source": [
        "#rs_vac = pd.read_csv('/content/drive/MyDrive/9.Colab Notebooks/RedeAnaliseCOVID-19/Codes/vacinas/RS_vacinas.csv', sep=';')\n",
        "#rs_vac.head(10)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "GcOgrXISJ313"
      },
      "source": [
        "Download to tempfile"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "N9ZIfZm4J7vl",
        "outputId": "751075eb-a930-42b1-b5b7-4370691073de"
      },
      "source": [
        "!wget -p https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-04-28/uf%3DRS/part-00000-7ab10ee1-6a0f-4ed9-b84c-9afb98b4efc2.c000.csv"
      ],
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "--2021-04-28 20:26:39--  https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-04-28/uf%3DRS/part-00000-7ab10ee1-6a0f-4ed9-b84c-9afb98b4efc2.c000.csv\n",
            "Resolving s3-sa-east-1.amazonaws.com (s3-sa-east-1.amazonaws.com)... 52.95.165.80\n",
            "Connecting to s3-sa-east-1.amazonaws.com (s3-sa-east-1.amazonaws.com)|52.95.165.80|:443... connected.\n",
            "HTTP request sent, awaiting response... 200 OK\n",
            "Length: 1711005641 (1.6G) [text/csv]\n",
            "Saving to: ‘s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-04-28/uf=RS/part-00000-7ab10ee1-6a0f-4ed9-b84c-9afb98b4efc2.c000.csv’\n",
            "\n",
            "s3-sa-east-1.amazon 100%[===================>]   1.59G  24.6MB/s    in 68s     \n",
            "\n",
            "2021-04-28 20:27:47 (24.1 MB/s) - ‘s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-04-28/uf=RS/part-00000-7ab10ee1-6a0f-4ed9-b84c-9afb98b4efc2.c000.csv’ saved [1711005641/1711005641]\n",
            "\n",
            "FINISHED --2021-04-28 20:27:47--\n",
            "Total wall clock time: 1m 8s\n",
            "Downloaded: 1 files, 1.6G in 1m 8s (24.1 MB/s)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "u0jfvyOVH0jp"
      },
      "source": [
        "import pandas as pd"
      ],
      "execution_count": 12,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 973
        },
        "id": "o1Ef0K3zICM0",
        "outputId": "3ecc70f7-c8ff-4ae5-98ef-62bd561ed752"
      },
      "source": [
        "rs_vac = pd.read_csv('/content/s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-04-28/uf=RS/part-00000-7ab10ee1-6a0f-4ed9-b84c-9afb98b4efc2.c000.csv', sep=\";\")\n",
        "rs_vac.head(10)"
      ],
      "execution_count": 14,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>document_id</th>\n",
              "      <th>paciente_id</th>\n",
              "      <th>paciente_idade</th>\n",
              "      <th>paciente_dataNascimento</th>\n",
              "      <th>paciente_enumSexoBiologico</th>\n",
              "      <th>paciente_racaCor_codigo</th>\n",
              "      <th>paciente_racaCor_valor</th>\n",
              "      <th>paciente_endereco_coIbgeMunicipio</th>\n",
              "      <th>paciente_endereco_coPais</th>\n",
              "      <th>paciente_endereco_nmMunicipio</th>\n",
              "      <th>paciente_endereco_nmPais</th>\n",
              "      <th>paciente_endereco_uf</th>\n",
              "      <th>paciente_endereco_cep</th>\n",
              "      <th>paciente_nacionalidade_enumNacionalidade</th>\n",
              "      <th>estabelecimento_valor</th>\n",
              "      <th>estabelecimento_razaoSocial</th>\n",
              "      <th>estalecimento_noFantasia</th>\n",
              "      <th>estabelecimento_municipio_codigo</th>\n",
              "      <th>estabelecimento_municipio_nome</th>\n",
              "      <th>estabelecimento_uf</th>\n",
              "      <th>vacina_grupoAtendimento_codigo</th>\n",
              "      <th>vacina_grupoAtendimento_nome</th>\n",
              "      <th>vacina_categoria_codigo</th>\n",
              "      <th>vacina_categoria_nome</th>\n",
              "      <th>vacina_lote</th>\n",
              "      <th>vacina_fabricante_nome</th>\n",
              "      <th>vacina_fabricante_referencia</th>\n",
              "      <th>vacina_dataAplicacao</th>\n",
              "      <th>vacina_descricao_dose</th>\n",
              "      <th>vacina_codigo</th>\n",
              "      <th>vacina_nome</th>\n",
              "      <th>sistema_origem</th>\n",
              "      <th>data_importacao_rnds</th>\n",
              "      <th>id_sistema_origem</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>a8b602f5-ddb2-4e25-a4ce-c83c4f9b2320-i0b0</td>\n",
              "      <td>db80043b47b3751412afbb0d4e35ed57c3fa55674d3a0c...</td>\n",
              "      <td>73</td>\n",
              "      <td>1947-12-24</td>\n",
              "      <td>F</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>430605.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>CRISTAL</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>96195.0</td>\n",
              "      <td>B</td>\n",
              "      <td>6299318</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE CRISTAL</td>\n",
              "      <td>CENTRO DE SAUDE CRISTAL</td>\n",
              "      <td>430605</td>\n",
              "      <td>CRISTAL</td>\n",
              "      <td>RS</td>\n",
              "      <td>203</td>\n",
              "      <td>Pessoas de 70 a 74 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>210075</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-20T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-24 17:31:01</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>21a160a7-b513-4b63-a6bf-6544376a8a80-i0b0</td>\n",
              "      <td>e14e02c98c45cd702ab6b9f060262d544c7b8f0a0caba8...</td>\n",
              "      <td>66</td>\n",
              "      <td>1954-06-30</td>\n",
              "      <td>F</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>431800.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>SAO BORJA</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>97670.0</td>\n",
              "      <td>B</td>\n",
              "      <td>2247631</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE SAO BORJA</td>\n",
              "      <td>CENTRO MUNICIPAL DE ATENDIMENTO ESPECIALIZADO ...</td>\n",
              "      <td>431800</td>\n",
              "      <td>SAO BORJA</td>\n",
              "      <td>RS</td>\n",
              "      <td>905</td>\n",
              "      <td>Cuidador de Idosos</td>\n",
              "      <td>9.0</td>\n",
              "      <td>Trabalhadores de Saúde</td>\n",
              "      <td>210048</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-18T03:00:00.000Z</td>\n",
              "      <td>2ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-19 12:03:16</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>0ae299b9-cff4-4bd2-bdfd-09d47514b97c-i0b0</td>\n",
              "      <td>e045879e426db9af1619a8129deef30a58ca4cd65f4ecb...</td>\n",
              "      <td>68</td>\n",
              "      <td>1953-03-05</td>\n",
              "      <td>F</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>430640.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>DOIS IRMAOS</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>93950.0</td>\n",
              "      <td>B</td>\n",
              "      <td>2701251</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE DOIS IRMAOS</td>\n",
              "      <td>POSTINHO CENTRO US CENTRO DIRMAOS</td>\n",
              "      <td>430640</td>\n",
              "      <td>DOIS IRMAOS</td>\n",
              "      <td>RS</td>\n",
              "      <td>202</td>\n",
              "      <td>Pessoas de 65 a 69 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>210107</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-31T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-04-01 22:47:41</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>31b8095d-e8cb-4825-b43a-c46166952270-i0b0</td>\n",
              "      <td>28c703c3617a3d598d6224053ce21c08f34d5c9494cba8...</td>\n",
              "      <td>51</td>\n",
              "      <td>1969-06-18</td>\n",
              "      <td>F</td>\n",
              "      <td>99</td>\n",
              "      <td>SEM INFORMACAO</td>\n",
              "      <td>431490.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>PORTO ALEGRE</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>90610.0</td>\n",
              "      <td>B</td>\n",
              "      <td>7250479</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE PORTO ALEGRE</td>\n",
              "      <td>GERENCIA DISTRITAL CENTRO</td>\n",
              "      <td>431490</td>\n",
              "      <td>PORTO ALEGRE</td>\n",
              "      <td>RS</td>\n",
              "      <td>905</td>\n",
              "      <td>Cuidador de Idosos</td>\n",
              "      <td>9.0</td>\n",
              "      <td>Trabalhadores de Saúde</td>\n",
              "      <td>202010020</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-03T03:00:00.000Z</td>\n",
              "      <td>2ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-16 18:42:39</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>c36faa51-f831-4633-9677-fd432ffccb84-i0b0</td>\n",
              "      <td>34c5b8566e59cf09ce68224ef6a5ef14475c3ea3d53dbd...</td>\n",
              "      <td>73</td>\n",
              "      <td>1948-03-19</td>\n",
              "      <td>F</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>430230.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>BOM JESUS</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>95290.0</td>\n",
              "      <td>B</td>\n",
              "      <td>2236486</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE BOM JESUS</td>\n",
              "      <td>SECRETARIA MUNICIPAL DE SAUDE</td>\n",
              "      <td>430230</td>\n",
              "      <td>BOM JESUS</td>\n",
              "      <td>RS</td>\n",
              "      <td>203</td>\n",
              "      <td>Pessoas de 70 a 74 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>210075</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-23T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-23 18:00:31</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>579fc2ed-fc00-4277-b961-464994035a29-i0b0</td>\n",
              "      <td>58fe83075ac7bbfd11ccbd2092715bb5a558ee90bc0c3e...</td>\n",
              "      <td>70</td>\n",
              "      <td>1951-02-21</td>\n",
              "      <td>F</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>430390.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>CAMPO BOM</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>93700.0</td>\n",
              "      <td>B</td>\n",
              "      <td>7286627</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE CAMPO BOM</td>\n",
              "      <td>UNIDADE BASICA DE SAUDE MONACO</td>\n",
              "      <td>430390</td>\n",
              "      <td>CAMPO BOM</td>\n",
              "      <td>RS</td>\n",
              "      <td>203</td>\n",
              "      <td>Pessoas de 70 a 74 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>210086</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-26T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-29 19:54:15</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>6d59cf70-8b9a-45e5-845a-11703bcc7e05-i0b0</td>\n",
              "      <td>55423cfb1b755e12019b35c0cc96d98a1191de6460d944...</td>\n",
              "      <td>76</td>\n",
              "      <td>1944-07-09</td>\n",
              "      <td>M</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>431720.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>SANTA ROSA</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>98900.0</td>\n",
              "      <td>B</td>\n",
              "      <td>2254336</td>\n",
              "      <td>FUNDACAO MUNICIPAL DE SAUDE</td>\n",
              "      <td>UNIDADE BASICA DE SAUDE CRUZEIRO</td>\n",
              "      <td>431720</td>\n",
              "      <td>SANTA ROSA</td>\n",
              "      <td>RS</td>\n",
              "      <td>204</td>\n",
              "      <td>Pessoas de 75 a 79 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>210051</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-19T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-19 17:07:38</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>942040d9-b757-4133-a65b-01df8d582953-i0b0</td>\n",
              "      <td>0adebe3d1d56e99cbe99f3b9572306f986612f41dc6233...</td>\n",
              "      <td>66</td>\n",
              "      <td>1954-05-08</td>\n",
              "      <td>M</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>432210.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>TUCUNDUVA</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>98930.0</td>\n",
              "      <td>B</td>\n",
              "      <td>2250217</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE TUCUNDUVA</td>\n",
              "      <td>POSTO DE SAUDE 02</td>\n",
              "      <td>432210</td>\n",
              "      <td>TUCUNDUVA</td>\n",
              "      <td>RS</td>\n",
              "      <td>202</td>\n",
              "      <td>Pessoas de 65 a 69 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>212VCD001ZVA</td>\n",
              "      <td>FUNDACAO OSWALDO CRUZ</td>\n",
              "      <td>Organization/33781055000135</td>\n",
              "      <td>2021-03-26T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>85</td>\n",
              "      <td>Vacina Covid-19 - Covishield</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-29 16:53:19</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>1db54db4-be18-4607-a2fb-6c15b8d5aaad-i0b0</td>\n",
              "      <td>692a10a246422c8f5acca797b2b92f615f2af11c118cc1...</td>\n",
              "      <td>67</td>\n",
              "      <td>1953-07-30</td>\n",
              "      <td>M</td>\n",
              "      <td>1</td>\n",
              "      <td>BRANCA</td>\n",
              "      <td>430905.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>GLORINHA</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>94380.0</td>\n",
              "      <td>B</td>\n",
              "      <td>8011060</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE PORTO ALEGRE</td>\n",
              "      <td>DIRETORIA GERAL DE VIGILANCIA EM SAUDE</td>\n",
              "      <td>431490</td>\n",
              "      <td>PORTO ALEGRE</td>\n",
              "      <td>RS</td>\n",
              "      <td>202</td>\n",
              "      <td>Pessoas de 65 a 69 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>210107</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-31T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-04-08 19:22:54</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>f18f0790-f2ad-481c-859f-a304e0ee90c5-i0b0</td>\n",
              "      <td>19709619104fb3bc14e4a513ea6a3585d25067067952a5...</td>\n",
              "      <td>85</td>\n",
              "      <td>1935-06-16</td>\n",
              "      <td>F</td>\n",
              "      <td>99</td>\n",
              "      <td>SEM INFORMACAO</td>\n",
              "      <td>430460.0</td>\n",
              "      <td>10.0</td>\n",
              "      <td>CANOAS</td>\n",
              "      <td>BRASIL</td>\n",
              "      <td>RS</td>\n",
              "      <td>92310.0</td>\n",
              "      <td>B</td>\n",
              "      <td>2230135</td>\n",
              "      <td>PREFEITURA MUNICIPAL DE CANOAS</td>\n",
              "      <td>UBS MOVEL CANOAS</td>\n",
              "      <td>430460</td>\n",
              "      <td>CANOAS</td>\n",
              "      <td>RS</td>\n",
              "      <td>204</td>\n",
              "      <td>Pessoas de 75 a 79 anos</td>\n",
              "      <td>2.0</td>\n",
              "      <td>Faixa Etária</td>\n",
              "      <td>210051</td>\n",
              "      <td>FUNDACAO BUTANTAN</td>\n",
              "      <td>Organization/61189445000156</td>\n",
              "      <td>2021-03-13T03:00:00.000Z</td>\n",
              "      <td>1ª Dose</td>\n",
              "      <td>86</td>\n",
              "      <td>Covid-19-Coronavac-Sinovac/Butantan</td>\n",
              "      <td>Novo PNI</td>\n",
              "      <td>2021-03-13 18:32:43</td>\n",
              "      <td>16341</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "                                 document_id  ... id_sistema_origem\n",
              "0  a8b602f5-ddb2-4e25-a4ce-c83c4f9b2320-i0b0  ...             16341\n",
              "1  21a160a7-b513-4b63-a6bf-6544376a8a80-i0b0  ...             16341\n",
              "2  0ae299b9-cff4-4bd2-bdfd-09d47514b97c-i0b0  ...             16341\n",
              "3  31b8095d-e8cb-4825-b43a-c46166952270-i0b0  ...             16341\n",
              "4  c36faa51-f831-4633-9677-fd432ffccb84-i0b0  ...             16341\n",
              "5  579fc2ed-fc00-4277-b961-464994035a29-i0b0  ...             16341\n",
              "6  6d59cf70-8b9a-45e5-845a-11703bcc7e05-i0b0  ...             16341\n",
              "7  942040d9-b757-4133-a65b-01df8d582953-i0b0  ...             16341\n",
              "8  1db54db4-be18-4607-a2fb-6c15b8d5aaad-i0b0  ...             16341\n",
              "9  f18f0790-f2ad-481c-859f-a304e0ee90c5-i0b0  ...             16341\n",
              "\n",
              "[10 rows x 34 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 14
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Nvyum0zHLpc5"
      },
      "source": [
        "[REF](https://www.youtube.com/watch?v=sbOnV78uoys)actor by\n",
        "\n",
        "@author: bragatte"
      ]
    }
  ]
}