# -*- coding: utf-8 -*-
"""Seaborn0.11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/BragatteMAS/Python_Learning/blob/master/Colab_Pratice/Seaborn0_11.ipynb

'''
100daysofcode

"How to display change Statistical_test"

Refactor by  @bragatte ^202101132240

Day 5

[Seaborn 0.11 Updates](https://towardsdatascience.com/seaborn-0-11-just-released-with-great-new-features-c5b45efad7e2)
'''
"""

!pip install seaborn==0.11.0

sns.displot(data=diabetes, x='Glucose', kind='hist', height=6, aspect=1.2)

sns.displot(data=diabetes, x='Glucose', y='BloodPressure',
kind='hist', height=6, aspect=1.2)

sns.histplot(data=diabetes, x='Glucose', y='BloodPressure')

"""
[Churn](https://www.kaggle.com/sonalidasgupta95/churn-prediction-of-bank-customers)"""

sns.displot(data=churn, x='CreditScore', kind='hist',
col='Geography', hue='Exited')

sns.displot(data=churn, x='Age', kind='ecdf', col='Geography', hue='Exited')

sns.jointplot(data=diabetes, x='Insulin', y='BMI', hue='Outcome',
height=7)

sns.jointplot(data=diabetes, x='Insulin', y='BMI', hue='Outcome',
kind='hist', height=7)

"""Set function has been renamed as set_theme. It adjusts several properties of the theme used in visualizations.

The axlabel function is no longer available. It is recommended to use ax.set(xlabel=, ylabel=) instead.
"""