nt = int(input('Coloque aqui o número para ver a sua tabuada:'))
#t1 = int(nt * 1), (nt * 2)
t1 = int(nt * 1)
t2 = int(nt * 2)
t3 = int(nt * 3)
t4 = int(nt * 4)
t5 = int(nt * 5)
t6 = int(nt * 6)
t7 = int(nt * 7)
t8 = int(nt * 8)
t9 = int(nt * 9)
t10 = int(nt * 10)
print(f'A tabuada abaixo é do número {nt}: \n {nt}*1={t1} \n {nt}*2={t2} \n {nt}*3={t3} \n {nt}*4={t4} \n {nt}*5={t5} \n ...')

